# http://goreleaser.com
before:
  hooks:
  - go mod download

builds:
- binary: appland
  env:
  - CGO_ENABLED=0

  ldflags:
  - -s -w -X github.com/applandinc/appland-cli/internal/build.Version={{.Version}}

  goos:
  - linux
  - darwin
  - windows
  
  goarch:
  - amd64

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs\s*(\(.*\))?\s*:'
    - '^test\s*(\(.*\))?\s*:'
    - '^chore\s*(\(.*\))?\s*:'
    - '^build\s*(\(.*\))?\s*:'
    - '^ci\s*(\(.*\))?\s*:'
    - '\[skip ci\]$'
