plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  - - '@semantic-release/exec'
    - verifyConditionsCmd:
        'curl -sfL https://git.io/goreleaser | sh -s -- check'
      publishCmd: 'curl -sL https://git.io/goreleaser | bash'
