language: go
os: linux
script:
  - ./bin/test

matrix:
  include:
    - go: 1.14

before_deploy:
  - |
    nvm install --lts \
      && nvm use --lts \
      && npm i -g \
        semantic-release \
        @semantic-release/exec \
        @semantic-release/git \
        @semantic-release/changelog

deploy:
  provider: script
  script: semantic-release
  on:
    branch: master
